version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    ports:
      - 8000:8000
    networks:
      - mynetwork

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:
