# Generated by Django 4.1.7 on 2023-04-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
