# Generated by Django 4.1.7 on 2023-05-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_answer_like_question_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
